### ISSUE TITLE
Enable server configuration via a yaml file

### ISSUE THREAD

**Issue by MichaelKreil** [versatiles-org/versatiles-rs#25]
Could use: https://lib.rs/crates/clap_conf

**Comment by MichaelKreil** [comment]
Here's an example configuration file showing how a VersaTiles server could be configured using YAML.
All fields are optional — every setting has a sensible default fallback.

You can start the server using:
```bash
versatiles serve --config config.yaml
# or
versatiles serve -c config.yaml
```

What do you think?

```yaml
# VersaTiles server configuration example

server:
  ip: 0.0.0.0
  port: 8080
  fast: false

defaults:
  transforms:
    flip_y: false
    swap_xy: false
  default_input_compression: none

# --- CORS & Headers ----------------------------------------------------------
# CORS applies to API and tile/static responses.
cors:
  # List of allowed origins. Supports glob patterns.
  allowed_origins:
    - "https://example.org"
    - "*.other-example.org"
    - "null"

  # Which HTTP methods to allow in CORS preflights.
  allowed_methods: [GET, HEAD, OPTIONS]

  # Which request headers the browser may send.
  allowed_headers: [Accept, Accept-Encoding, Range, If-None-Match, If-Modified-Since]

  # Which response headers the browser can read from JS (beyond the simple ones).
  expose_headers: [ETag, Content-Length, Accept-Ranges]

  # If true, include: Access-Control-Allow-Credentials: true
  # (Note: cannot be combined with a wildcard '*' origin; must echo the matched origin.)
  allow_credentials: false

  # Preflight cache duration in seconds (Access-Control-Max-Age).
  max_age_seconds: 86400

# Extra response headers (useful behind CDNs). Keys are case-insensitive.
# These are added to every HTTP response. If a header already exists, this overrides it.
extra_response_headers:
  # Encourage long-lived caching for immutable tiles while letting the CDN keep longer.
  Cache-Control: "public, max-age=86400, immutable"
  # For CDNs that honor surrogate controls (Fastly, Varnish):
  Surrogate-Control: "max-age=604800"
  # Some CDNs read this separately (Cloudflare, etc.)
  CDN-Cache-Control: "max-age=604800"
  # Useful for resource timing across origins; align with your CORS policy.
  Timing-Allow-Origin: "*"

# --- Static mounts -----------------------------------------------------------
static:
  - path: "/web/site.tar.br"
    url_prefix: "/"
  - path: "assets/"
    url_prefix: "/assets"

# --- Tile sources ------------------------------------------------------------
tiles:
  - name: osm
    path: "https://download.versatiles.org/osm.versatiles"
    transforms: { flip_y: false, swap_xy: false }
    input_compression: none

  - name: berlin
    path: "../testdata/berlin.mbtiles"

  - name: planet
    path: "/data/tiles/planet.tar.br"
    transforms: { flip_y: true, swap_xy: true }

# --- Optional includes -------------------------------------------------------
include:
  files:
    - "extras/maps.yaml"
    - "extras/static.yaml"
```
